# Generated by Django 4.2.5 on 2023-09-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0002_ingredients_recipes_types_of_recipes_units_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes_ingredients',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
