# Generated by Django 4.2.5 on 2023-09-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0003_alter_recipes_ingredients_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='image',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
