# Generated by Django 4.2.5 on 2023-10-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0004_recipes_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='subscription_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
